---
- hosts: tom
  become: yes
  tasks:
  - name: Install tomcat
    yum:
      name: tomcat
      state: present
  - name: Install Admin and online documents
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - tomcat-webapps
      - tomcat-admin-webapps
  - name: Configure Tomcat Web Management Interface
    copy:
      src: tomcat-users.xml
      dest: /usr/share/tomcat/conf/tomcat-users.xml
  - name: Start Tomcat
    service:
      name: tomcat
      state: started
  - name: restart Tomcat
    service:
      name: tomcat
      state: restarted
  - name: Enable Tomcat Service
    service:
      name: tomcat
      enabled: yes

