---
- hosts: all
  become: yes
  vars:
    - myname: template examples
  tasks:
  - name: creating a file with static content
    copy:
      src: test.txt
      dest: /home/ansible/hello.txt
  - name: craeating a file with dynamic value
    template:
      src: test.j2
      dest: /home/ansible/san